language: node_js
node_js:
  - 6

cache:
  yarn: true
  directories:
    - node_modules

before_script:
    - echo "About to deploy"

script:
    - echo "Deploying !"
    - yarn
    - yarn build

install:
    - npm install -g firebase-tools

after_success:
    - firebase deploy --only hosting --token $FIREBASE_TOKEN_ANDY
    - echo "Successfully deployed"

branches:
  only:
  - master

notifications:
  email: false